branches:
  only:
    - master
    - integration
    - /-ci$/

dist: trusty
sudo: required
group: deprecated-2017Q2

language: c

services:
  - docker

env:
  - PGB_TEST_VM="co6" PGB_TEST_PARAM=""
  - PGB_TEST_VM="u16" PGB_TEST_PARAM=" --no-lint"
  - PGB_TEST_VM="co7" PGB_TEST_PARAM=" --no-lint"
  - PGB_TEST_VM="u14" PGB_TEST_PARAM=" --no-lint"

before_install:
  - sudo apt-get -qq update && sudo apt-get install libxml-checker-perl libdbd-pg-perl libperl-critic-perl libtemplate-perl libpod-coverage-perl libtest-differences-perl libhtml-parser-perl lintian debhelper txt2man devscripts libjson-perl libio-socket-ssl-perl libxml-libxml-perl python-pip
  - |
    # Install & Configure AWS CLI
    pip install --upgrade --user awscli
    aws configure set region us-east-1
    aws configure set aws_access_key_id accessKey1
    aws configure set aws_secret_access_key verySecretKey1
    aws help --version
    aws configure list
  - |
    # Install Devel::Cover
    sudo dpkg -i ${TRAVIS_BUILD_DIR?}/test/package/u14-libdevel-cover-perl_1.23-2_amd64.deb
    /usr/bin/cover -v

install:
  - |
    # User Configuration
    sudo adduser --ingroup=${USER?} --disabled-password --gecos "" backrest
    umask 0022
    cd ~ && pwd && whoami && umask && groups
    mv ${TRAVIS_BUILD_DIR?} pgbackrest
    rm -rf ${TRAVIS_BUILD_DIR?}
  - pgbackrest/test/test.pl --vm-build --vm=${PGB_TEST_VM?}

script:
  - pgbackrest/test/test.pl --vm-max=2 --vm-host=u14 --vm=${PGB_TEST_VM?} ${PGB_TEST_PARAM?}
